### ISSUE TITLE
cpanel migration - no spamassassain rule migrated

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#943]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  10 package updates are available  |

This is a probably a feature request.

## Background

In cpanel I have set a few spamassassain rules to block out most of the offenders of recent spam in `Global Email Filters`. these are per domain rules.

You can also set `Email Filters` which is a per email method.

![image](https://github.com/user-attachments/assets/a5d5f3f3-2596-4741-b41a-76d2b6ebab88)

## the issue

My global filters/spamassaasain rules were not brought over

## the request

Make the cpanel migration migrate these settings aswell.

NB: Mine are not complex and i can move them manually.

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

Where are those SpamAssassin rules stored within a cPanel account?

**Comment by shoulders** [comment]
Below id the information you have asked for but for SpamAssassin rules and the filters, both of which were not brought over.

## in the cpanel account backup

`./homdedir/.cpanel/filter.yaml.bak`

this is from 2017 so I think it is pointless and not the live data.


`./homdedir/.cpanel/filter.yaml`
<details>
```yaml
--- 
filter: 
  - 
    actions: 
      - 
        action: save
        dest: /dev/null
    filtername: Dodgy Spam
    rules: 
      - 
        match: contains
        opt: or
        part: $message_body
        val: /t/click/
      - 
        match: contains
        opt: or
        part: $message_body
        val: /mw/index.php/
      - 
        match: contains
        opt: or
        part: $message_body
        val: or send post-mail
      - 
        match: contains
        opt: or
        part: $message_body
        val: /track-url/
      - 
        match: contains
        opt: or
        part: $message_body
        val: claudia
    unescaped: 1
  - 
    actions: 
      - 
        action: save
        dest: /dev/null
    enabled: 1
    filtername: Generated Apache SpamAssassin™ Discard Rule
    rules: 
      - 
        match: contains
        opt: or
        part: "$h_X-Spam-Bar:"
        val: +++++
version: '2.2'
```
</details>

`./homdedir/.cpanel/filter.cache`

```json
{"version":2.2,"filter":[{"actions":[{"dest":"/dev/null","action":"save"}],"filtername":"Dodgy Spam","unescaped":1,"rules":[{"val":"/t/click/","part":"$message_body","opt":"or","match":"contains"},{"val":"/mw/index.php/","part":"$message_body","match":"contains","opt":"or"},{"val":"or send post-mail","part":"$message_body","match":"contains","opt":"or"},{"part":"$message_body","match":"contains","opt":"or","val":"/track-url/"},{"part":"$message_body","match":"contains","opt":"or","val":"claudia"}]},{"filtername":"Generated Apache SpamAssassin™ Discard Rule","rules":[{"val":"+++++","part":"$h_X-Spam-Bar:","opt":"or","match":"contains"}],"enabled":"1","actions":[{"dest":"/dev/null","action":"save"}]}]}
```

`./homdedir/.spamassassin/user_prefs`

```
score SPF_FAIL 10
whitelist_from *@joomlashine.com
whitelist_from *@stackideas.com
required_score 5
```

## Addtional

https://docs.cpanel.net/cpanel/files/backup-for-cpanel/

> The Email Filters backup file only stores the account-level email filters from cPanel’s [Global Email Filters](https://docs.cpanel.net/cpanel/email/global-email-filters/) interface (cPanel » Home » Email » Global Email Filters). The backup file does not store user account-level email filters from cPanel’s [Email Filters](https://docs.cpanel.net/cpanel/email/email-filters/) interface (cPanel » Home » Email » Email Filters).
